//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmitirMVM.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BonusPartNumberData", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class BonusPartNumberData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BonusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoDesenhoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string QtdeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescricaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoDesenhoNovoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Bonus {
            get {
                return this.BonusField;
            }
            set {
                if ((object.ReferenceEquals(this.BonusField, value) != true)) {
                    this.BonusField = value;
                    this.RaisePropertyChanged("Bonus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string CodigoDesenho {
            get {
                return this.CodigoDesenhoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoDesenhoField, value) != true)) {
                    this.CodigoDesenhoField = value;
                    this.RaisePropertyChanged("CodigoDesenho");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Qtde {
            get {
                return this.QtdeField;
            }
            set {
                if ((object.ReferenceEquals(this.QtdeField, value) != true)) {
                    this.QtdeField = value;
                    this.RaisePropertyChanged("Qtde");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Descricao {
            get {
                return this.DescricaoField;
            }
            set {
                if ((object.ReferenceEquals(this.DescricaoField, value) != true)) {
                    this.DescricaoField = value;
                    this.RaisePropertyChanged("Descricao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string CodigoDesenhoNovo {
            get {
                return this.CodigoDesenhoNovoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoDesenhoNovoField, value) != true)) {
                    this.CodigoDesenhoNovoField = value;
                    this.RaisePropertyChanged("CodigoDesenhoNovo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DadosMVM", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class DadosMVM : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HashField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmpresaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FornecedoresField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FornecedorEnvioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FornecedorTransportadoraField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeMotoristaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumeroRGMotoristaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumeroCPFMotoristaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoCNHMotoristaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumeroCNHMotoristaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DataValidadeCNHMotoristaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoVeiculoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescricaoMarcaVeiculoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumeroPlacaVeiculoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumeroPlacaCarretaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string QtdeAjudanteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumeroConhecimentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ObservacaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsuarioCriacaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VlrTotalMercadoriasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PesoBrutoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Hash {
            get {
                return this.HashField;
            }
            set {
                if ((object.ReferenceEquals(this.HashField, value) != true)) {
                    this.HashField = value;
                    this.RaisePropertyChanged("Hash");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Empresa {
            get {
                return this.EmpresaField;
            }
            set {
                if ((object.ReferenceEquals(this.EmpresaField, value) != true)) {
                    this.EmpresaField = value;
                    this.RaisePropertyChanged("Empresa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Fornecedores {
            get {
                return this.FornecedoresField;
            }
            set {
                if ((object.ReferenceEquals(this.FornecedoresField, value) != true)) {
                    this.FornecedoresField = value;
                    this.RaisePropertyChanged("Fornecedores");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string FornecedorEnvio {
            get {
                return this.FornecedorEnvioField;
            }
            set {
                if ((object.ReferenceEquals(this.FornecedorEnvioField, value) != true)) {
                    this.FornecedorEnvioField = value;
                    this.RaisePropertyChanged("FornecedorEnvio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string FornecedorTransportadora {
            get {
                return this.FornecedorTransportadoraField;
            }
            set {
                if ((object.ReferenceEquals(this.FornecedorTransportadoraField, value) != true)) {
                    this.FornecedorTransportadoraField = value;
                    this.RaisePropertyChanged("FornecedorTransportadora");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string NomeMotorista {
            get {
                return this.NomeMotoristaField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeMotoristaField, value) != true)) {
                    this.NomeMotoristaField = value;
                    this.RaisePropertyChanged("NomeMotorista");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string NumeroRGMotorista {
            get {
                return this.NumeroRGMotoristaField;
            }
            set {
                if ((object.ReferenceEquals(this.NumeroRGMotoristaField, value) != true)) {
                    this.NumeroRGMotoristaField = value;
                    this.RaisePropertyChanged("NumeroRGMotorista");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string NumeroCPFMotorista {
            get {
                return this.NumeroCPFMotoristaField;
            }
            set {
                if ((object.ReferenceEquals(this.NumeroCPFMotoristaField, value) != true)) {
                    this.NumeroCPFMotoristaField = value;
                    this.RaisePropertyChanged("NumeroCPFMotorista");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string TipoCNHMotorista {
            get {
                return this.TipoCNHMotoristaField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoCNHMotoristaField, value) != true)) {
                    this.TipoCNHMotoristaField = value;
                    this.RaisePropertyChanged("TipoCNHMotorista");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string NumeroCNHMotorista {
            get {
                return this.NumeroCNHMotoristaField;
            }
            set {
                if ((object.ReferenceEquals(this.NumeroCNHMotoristaField, value) != true)) {
                    this.NumeroCNHMotoristaField = value;
                    this.RaisePropertyChanged("NumeroCNHMotorista");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string DataValidadeCNHMotorista {
            get {
                return this.DataValidadeCNHMotoristaField;
            }
            set {
                if ((object.ReferenceEquals(this.DataValidadeCNHMotoristaField, value) != true)) {
                    this.DataValidadeCNHMotoristaField = value;
                    this.RaisePropertyChanged("DataValidadeCNHMotorista");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string TipoVeiculo {
            get {
                return this.TipoVeiculoField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoVeiculoField, value) != true)) {
                    this.TipoVeiculoField = value;
                    this.RaisePropertyChanged("TipoVeiculo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string DescricaoMarcaVeiculo {
            get {
                return this.DescricaoMarcaVeiculoField;
            }
            set {
                if ((object.ReferenceEquals(this.DescricaoMarcaVeiculoField, value) != true)) {
                    this.DescricaoMarcaVeiculoField = value;
                    this.RaisePropertyChanged("DescricaoMarcaVeiculo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string NumeroPlacaVeiculo {
            get {
                return this.NumeroPlacaVeiculoField;
            }
            set {
                if ((object.ReferenceEquals(this.NumeroPlacaVeiculoField, value) != true)) {
                    this.NumeroPlacaVeiculoField = value;
                    this.RaisePropertyChanged("NumeroPlacaVeiculo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string NumeroPlacaCarreta {
            get {
                return this.NumeroPlacaCarretaField;
            }
            set {
                if ((object.ReferenceEquals(this.NumeroPlacaCarretaField, value) != true)) {
                    this.NumeroPlacaCarretaField = value;
                    this.RaisePropertyChanged("NumeroPlacaCarreta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public string QtdeAjudante {
            get {
                return this.QtdeAjudanteField;
            }
            set {
                if ((object.ReferenceEquals(this.QtdeAjudanteField, value) != true)) {
                    this.QtdeAjudanteField = value;
                    this.RaisePropertyChanged("QtdeAjudante");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=16)]
        public string NumeroConhecimento {
            get {
                return this.NumeroConhecimentoField;
            }
            set {
                if ((object.ReferenceEquals(this.NumeroConhecimentoField, value) != true)) {
                    this.NumeroConhecimentoField = value;
                    this.RaisePropertyChanged("NumeroConhecimento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=17)]
        public string Observacao {
            get {
                return this.ObservacaoField;
            }
            set {
                if ((object.ReferenceEquals(this.ObservacaoField, value) != true)) {
                    this.ObservacaoField = value;
                    this.RaisePropertyChanged("Observacao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=18)]
        public string UsuarioCriacao {
            get {
                return this.UsuarioCriacaoField;
            }
            set {
                if ((object.ReferenceEquals(this.UsuarioCriacaoField, value) != true)) {
                    this.UsuarioCriacaoField = value;
                    this.RaisePropertyChanged("UsuarioCriacao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=19)]
        public string VlrTotalMercadorias {
            get {
                return this.VlrTotalMercadoriasField;
            }
            set {
                if ((object.ReferenceEquals(this.VlrTotalMercadoriasField, value) != true)) {
                    this.VlrTotalMercadoriasField = value;
                    this.RaisePropertyChanged("VlrTotalMercadorias");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=20)]
        public string PesoBruto {
            get {
                return this.PesoBrutoField;
            }
            set {
                if ((object.ReferenceEquals(this.PesoBrutoField, value) != true)) {
                    this.PesoBrutoField = value;
                    this.RaisePropertyChanged("PesoBruto");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IMvmSoapService")]
    public interface IMvmSoapService {
        
        // CODEGEN: Gerando contrato de mensagem porque o nome do elemento codigoEmpresa no namespace http://tempuri.org/ não está marcado como nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMvmSoapService/RegistrarBonus", ReplyAction="*")]
        EmitirMVM.ServiceReference1.RegistrarBonusResponse RegistrarBonus(EmitirMVM.ServiceReference1.RegistrarBonusRequest request);
        
        // CODEGEN: Gerando contrato de mensagem porque o nome do elemento dados no namespace http://tempuri.org/ não está marcado como nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMvmSoapService/EmitirMVM", ReplyAction="*")]
        EmitirMVM.ServiceReference1.EmitirMVMResponse EmitirMVM(EmitirMVM.ServiceReference1.EmitirMVMRequest request);
        
        // CODEGEN: Gerando contrato de mensagem porque o nome do elemento Metodo1Result no namespace http://tempuri.org/ não está marcado como nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMvmSoapService/Metodo1", ReplyAction="*")]
        EmitirMVM.ServiceReference1.Metodo1Response Metodo1(EmitirMVM.ServiceReference1.Metodo1Request request);
        
        // CODEGEN: Gerando contrato de mensagem porque o nome do elemento msg no namespace http://tempuri.org/ não está marcado como nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMvmSoapService/Metodo2", ReplyAction="*")]
        EmitirMVM.ServiceReference1.Metodo2Response Metodo2(EmitirMVM.ServiceReference1.Metodo2Request request);
        
        // CODEGEN: Gerando contrato de mensagem porque o nome do elemento obj no namespace http://tempuri.org/ não está marcado como nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMvmSoapService/Metodo3", ReplyAction="*")]
        EmitirMVM.ServiceReference1.Metodo3Response Metodo3(EmitirMVM.ServiceReference1.Metodo3Request request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegistrarBonusRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegistrarBonus", Namespace="http://tempuri.org/", Order=0)]
        public EmitirMVM.ServiceReference1.RegistrarBonusRequestBody Body;
        
        public RegistrarBonusRequest() {
        }
        
        public RegistrarBonusRequest(EmitirMVM.ServiceReference1.RegistrarBonusRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RegistrarBonusRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string codigoEmpresa;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string codigoMVM;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string chaveNFE;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string hash;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public EmitirMVM.ServiceReference1.BonusPartNumberData[] dadosPartNumber;
        
        public RegistrarBonusRequestBody() {
        }
        
        public RegistrarBonusRequestBody(string codigoEmpresa, string codigoMVM, string chaveNFE, string hash, EmitirMVM.ServiceReference1.BonusPartNumberData[] dadosPartNumber) {
            this.codigoEmpresa = codigoEmpresa;
            this.codigoMVM = codigoMVM;
            this.chaveNFE = chaveNFE;
            this.hash = hash;
            this.dadosPartNumber = dadosPartNumber;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegistrarBonusResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegistrarBonusResponse", Namespace="http://tempuri.org/", Order=0)]
        public EmitirMVM.ServiceReference1.RegistrarBonusResponseBody Body;
        
        public RegistrarBonusResponse() {
        }
        
        public RegistrarBonusResponse(EmitirMVM.ServiceReference1.RegistrarBonusResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RegistrarBonusResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string RegistrarBonusResult;
        
        public RegistrarBonusResponseBody() {
        }
        
        public RegistrarBonusResponseBody(string RegistrarBonusResult) {
            this.RegistrarBonusResult = RegistrarBonusResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EmitirMVMRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EmitirMVM", Namespace="http://tempuri.org/", Order=0)]
        public EmitirMVM.ServiceReference1.EmitirMVMRequestBody Body;
        
        public EmitirMVMRequest() {
        }
        
        public EmitirMVMRequest(EmitirMVM.ServiceReference1.EmitirMVMRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EmitirMVMRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public EmitirMVM.ServiceReference1.DadosMVM dados;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public EmitirMVM.ServiceReference1.ArrayOfString NotasFiscais;
        
        public EmitirMVMRequestBody() {
        }
        
        public EmitirMVMRequestBody(EmitirMVM.ServiceReference1.DadosMVM dados, EmitirMVM.ServiceReference1.ArrayOfString NotasFiscais) {
            this.dados = dados;
            this.NotasFiscais = NotasFiscais;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EmitirMVMResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EmitirMVMResponse", Namespace="http://tempuri.org/", Order=0)]
        public EmitirMVM.ServiceReference1.EmitirMVMResponseBody Body;
        
        public EmitirMVMResponse() {
        }
        
        public EmitirMVMResponse(EmitirMVM.ServiceReference1.EmitirMVMResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EmitirMVMResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string EmitirMVMResult;
        
        public EmitirMVMResponseBody() {
        }
        
        public EmitirMVMResponseBody(string EmitirMVMResult) {
            this.EmitirMVMResult = EmitirMVMResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Metodo1Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Metodo1", Namespace="http://tempuri.org/", Order=0)]
        public EmitirMVM.ServiceReference1.Metodo1RequestBody Body;
        
        public Metodo1Request() {
        }
        
        public Metodo1Request(EmitirMVM.ServiceReference1.Metodo1RequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class Metodo1RequestBody {
        
        public Metodo1RequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Metodo1Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Metodo1Response", Namespace="http://tempuri.org/", Order=0)]
        public EmitirMVM.ServiceReference1.Metodo1ResponseBody Body;
        
        public Metodo1Response() {
        }
        
        public Metodo1Response(EmitirMVM.ServiceReference1.Metodo1ResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Metodo1ResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Metodo1Result;
        
        public Metodo1ResponseBody() {
        }
        
        public Metodo1ResponseBody(string Metodo1Result) {
            this.Metodo1Result = Metodo1Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Metodo2Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Metodo2", Namespace="http://tempuri.org/", Order=0)]
        public EmitirMVM.ServiceReference1.Metodo2RequestBody Body;
        
        public Metodo2Request() {
        }
        
        public Metodo2Request(EmitirMVM.ServiceReference1.Metodo2RequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Metodo2RequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string msg;
        
        public Metodo2RequestBody() {
        }
        
        public Metodo2RequestBody(string msg) {
            this.msg = msg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Metodo2Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Metodo2Response", Namespace="http://tempuri.org/", Order=0)]
        public EmitirMVM.ServiceReference1.Metodo2ResponseBody Body;
        
        public Metodo2Response() {
        }
        
        public Metodo2Response(EmitirMVM.ServiceReference1.Metodo2ResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Metodo2ResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Metodo2Result;
        
        public Metodo2ResponseBody() {
        }
        
        public Metodo2ResponseBody(string Metodo2Result) {
            this.Metodo2Result = Metodo2Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Metodo3Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Metodo3", Namespace="http://tempuri.org/", Order=0)]
        public EmitirMVM.ServiceReference1.Metodo3RequestBody Body;
        
        public Metodo3Request() {
        }
        
        public Metodo3Request(EmitirMVM.ServiceReference1.Metodo3RequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Metodo3RequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public EmitirMVM.ServiceReference1.DadosMVM obj;
        
        public Metodo3RequestBody() {
        }
        
        public Metodo3RequestBody(EmitirMVM.ServiceReference1.DadosMVM obj) {
            this.obj = obj;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Metodo3Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Metodo3Response", Namespace="http://tempuri.org/", Order=0)]
        public EmitirMVM.ServiceReference1.Metodo3ResponseBody Body;
        
        public Metodo3Response() {
        }
        
        public Metodo3Response(EmitirMVM.ServiceReference1.Metodo3ResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Metodo3ResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Metodo3Result;
        
        public Metodo3ResponseBody() {
        }
        
        public Metodo3ResponseBody(string Metodo3Result) {
            this.Metodo3Result = Metodo3Result;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMvmSoapServiceChannel : EmitirMVM.ServiceReference1.IMvmSoapService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MvmSoapServiceClient : System.ServiceModel.ClientBase<EmitirMVM.ServiceReference1.IMvmSoapService>, EmitirMVM.ServiceReference1.IMvmSoapService {
        
        public MvmSoapServiceClient() {
        }
        
        public MvmSoapServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MvmSoapServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MvmSoapServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MvmSoapServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EmitirMVM.ServiceReference1.RegistrarBonusResponse EmitirMVM.ServiceReference1.IMvmSoapService.RegistrarBonus(EmitirMVM.ServiceReference1.RegistrarBonusRequest request) {
            return base.Channel.RegistrarBonus(request);
        }
        
        public string RegistrarBonus(string codigoEmpresa, string codigoMVM, string chaveNFE, string hash, EmitirMVM.ServiceReference1.BonusPartNumberData[] dadosPartNumber) {
            EmitirMVM.ServiceReference1.RegistrarBonusRequest inValue = new EmitirMVM.ServiceReference1.RegistrarBonusRequest();
            inValue.Body = new EmitirMVM.ServiceReference1.RegistrarBonusRequestBody();
            inValue.Body.codigoEmpresa = codigoEmpresa;
            inValue.Body.codigoMVM = codigoMVM;
            inValue.Body.chaveNFE = chaveNFE;
            inValue.Body.hash = hash;
            inValue.Body.dadosPartNumber = dadosPartNumber;
            EmitirMVM.ServiceReference1.RegistrarBonusResponse retVal = ((EmitirMVM.ServiceReference1.IMvmSoapService)(this)).RegistrarBonus(inValue);
            return retVal.Body.RegistrarBonusResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EmitirMVM.ServiceReference1.EmitirMVMResponse EmitirMVM.ServiceReference1.IMvmSoapService.EmitirMVM(EmitirMVM.ServiceReference1.EmitirMVMRequest request) {
            return base.Channel.EmitirMVM(request);
        }
        
        public string EmitirMVM(EmitirMVM.ServiceReference1.DadosMVM dados, EmitirMVM.ServiceReference1.ArrayOfString NotasFiscais) {
            EmitirMVM.ServiceReference1.EmitirMVMRequest inValue = new EmitirMVM.ServiceReference1.EmitirMVMRequest();
            inValue.Body = new EmitirMVM.ServiceReference1.EmitirMVMRequestBody();
            inValue.Body.dados = dados;
            inValue.Body.NotasFiscais = NotasFiscais;
            EmitirMVM.ServiceReference1.EmitirMVMResponse retVal = ((EmitirMVM.ServiceReference1.IMvmSoapService)(this)).EmitirMVM(inValue);
            return retVal.Body.EmitirMVMResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EmitirMVM.ServiceReference1.Metodo1Response EmitirMVM.ServiceReference1.IMvmSoapService.Metodo1(EmitirMVM.ServiceReference1.Metodo1Request request) {
            return base.Channel.Metodo1(request);
        }
        
        public string Metodo1() {
            EmitirMVM.ServiceReference1.Metodo1Request inValue = new EmitirMVM.ServiceReference1.Metodo1Request();
            inValue.Body = new EmitirMVM.ServiceReference1.Metodo1RequestBody();
            EmitirMVM.ServiceReference1.Metodo1Response retVal = ((EmitirMVM.ServiceReference1.IMvmSoapService)(this)).Metodo1(inValue);
            return retVal.Body.Metodo1Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EmitirMVM.ServiceReference1.Metodo2Response EmitirMVM.ServiceReference1.IMvmSoapService.Metodo2(EmitirMVM.ServiceReference1.Metodo2Request request) {
            return base.Channel.Metodo2(request);
        }
        
        public string Metodo2(string msg) {
            EmitirMVM.ServiceReference1.Metodo2Request inValue = new EmitirMVM.ServiceReference1.Metodo2Request();
            inValue.Body = new EmitirMVM.ServiceReference1.Metodo2RequestBody();
            inValue.Body.msg = msg;
            EmitirMVM.ServiceReference1.Metodo2Response retVal = ((EmitirMVM.ServiceReference1.IMvmSoapService)(this)).Metodo2(inValue);
            return retVal.Body.Metodo2Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EmitirMVM.ServiceReference1.Metodo3Response EmitirMVM.ServiceReference1.IMvmSoapService.Metodo3(EmitirMVM.ServiceReference1.Metodo3Request request) {
            return base.Channel.Metodo3(request);
        }
        
        public string Metodo3(EmitirMVM.ServiceReference1.DadosMVM obj) {
            EmitirMVM.ServiceReference1.Metodo3Request inValue = new EmitirMVM.ServiceReference1.Metodo3Request();
            inValue.Body = new EmitirMVM.ServiceReference1.Metodo3RequestBody();
            inValue.Body.obj = obj;
            EmitirMVM.ServiceReference1.Metodo3Response retVal = ((EmitirMVM.ServiceReference1.IMvmSoapService)(this)).Metodo3(inValue);
            return retVal.Body.Metodo3Result;
        }
    }
}
