//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmitirMVM.MVMCreate2 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DadosMVM", Namespace="http://schemas.datacontract.org/2004/07/IBM.FiatGroup.AE.WcfServices.Contracts.Se" +
        "rvices")]
    [System.SerializableAttribute()]
    public partial class DadosMVM : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DataValidadeCNHMotoristaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescricaoMarcaVeiculoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmpresaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FornecedorEnvioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FornecedorTransportadoraField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FornecedoresField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HashField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeMotoristaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumeroCNHMotoristaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumeroCPFMotoristaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumeroConhecimentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumeroPlacaCarretaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumeroPlacaVeiculoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumeroRGMotoristaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ObservacaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string QtdeAjudanteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoCNHMotoristaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoVeiculoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsuarioCriacaoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DataValidadeCNHMotorista {
            get {
                return this.DataValidadeCNHMotoristaField;
            }
            set {
                if ((object.ReferenceEquals(this.DataValidadeCNHMotoristaField, value) != true)) {
                    this.DataValidadeCNHMotoristaField = value;
                    this.RaisePropertyChanged("DataValidadeCNHMotorista");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DescricaoMarcaVeiculo {
            get {
                return this.DescricaoMarcaVeiculoField;
            }
            set {
                if ((object.ReferenceEquals(this.DescricaoMarcaVeiculoField, value) != true)) {
                    this.DescricaoMarcaVeiculoField = value;
                    this.RaisePropertyChanged("DescricaoMarcaVeiculo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Empresa {
            get {
                return this.EmpresaField;
            }
            set {
                if ((object.ReferenceEquals(this.EmpresaField, value) != true)) {
                    this.EmpresaField = value;
                    this.RaisePropertyChanged("Empresa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FornecedorEnvio {
            get {
                return this.FornecedorEnvioField;
            }
            set {
                if ((object.ReferenceEquals(this.FornecedorEnvioField, value) != true)) {
                    this.FornecedorEnvioField = value;
                    this.RaisePropertyChanged("FornecedorEnvio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FornecedorTransportadora {
            get {
                return this.FornecedorTransportadoraField;
            }
            set {
                if ((object.ReferenceEquals(this.FornecedorTransportadoraField, value) != true)) {
                    this.FornecedorTransportadoraField = value;
                    this.RaisePropertyChanged("FornecedorTransportadora");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Fornecedores {
            get {
                return this.FornecedoresField;
            }
            set {
                if ((object.ReferenceEquals(this.FornecedoresField, value) != true)) {
                    this.FornecedoresField = value;
                    this.RaisePropertyChanged("Fornecedores");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Hash {
            get {
                return this.HashField;
            }
            set {
                if ((object.ReferenceEquals(this.HashField, value) != true)) {
                    this.HashField = value;
                    this.RaisePropertyChanged("Hash");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NomeMotorista {
            get {
                return this.NomeMotoristaField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeMotoristaField, value) != true)) {
                    this.NomeMotoristaField = value;
                    this.RaisePropertyChanged("NomeMotorista");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumeroCNHMotorista {
            get {
                return this.NumeroCNHMotoristaField;
            }
            set {
                if ((object.ReferenceEquals(this.NumeroCNHMotoristaField, value) != true)) {
                    this.NumeroCNHMotoristaField = value;
                    this.RaisePropertyChanged("NumeroCNHMotorista");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumeroCPFMotorista {
            get {
                return this.NumeroCPFMotoristaField;
            }
            set {
                if ((object.ReferenceEquals(this.NumeroCPFMotoristaField, value) != true)) {
                    this.NumeroCPFMotoristaField = value;
                    this.RaisePropertyChanged("NumeroCPFMotorista");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumeroConhecimento {
            get {
                return this.NumeroConhecimentoField;
            }
            set {
                if ((object.ReferenceEquals(this.NumeroConhecimentoField, value) != true)) {
                    this.NumeroConhecimentoField = value;
                    this.RaisePropertyChanged("NumeroConhecimento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumeroPlacaCarreta {
            get {
                return this.NumeroPlacaCarretaField;
            }
            set {
                if ((object.ReferenceEquals(this.NumeroPlacaCarretaField, value) != true)) {
                    this.NumeroPlacaCarretaField = value;
                    this.RaisePropertyChanged("NumeroPlacaCarreta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumeroPlacaVeiculo {
            get {
                return this.NumeroPlacaVeiculoField;
            }
            set {
                if ((object.ReferenceEquals(this.NumeroPlacaVeiculoField, value) != true)) {
                    this.NumeroPlacaVeiculoField = value;
                    this.RaisePropertyChanged("NumeroPlacaVeiculo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumeroRGMotorista {
            get {
                return this.NumeroRGMotoristaField;
            }
            set {
                if ((object.ReferenceEquals(this.NumeroRGMotoristaField, value) != true)) {
                    this.NumeroRGMotoristaField = value;
                    this.RaisePropertyChanged("NumeroRGMotorista");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Observacao {
            get {
                return this.ObservacaoField;
            }
            set {
                if ((object.ReferenceEquals(this.ObservacaoField, value) != true)) {
                    this.ObservacaoField = value;
                    this.RaisePropertyChanged("Observacao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string QtdeAjudante {
            get {
                return this.QtdeAjudanteField;
            }
            set {
                if ((object.ReferenceEquals(this.QtdeAjudanteField, value) != true)) {
                    this.QtdeAjudanteField = value;
                    this.RaisePropertyChanged("QtdeAjudante");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoCNHMotorista {
            get {
                return this.TipoCNHMotoristaField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoCNHMotoristaField, value) != true)) {
                    this.TipoCNHMotoristaField = value;
                    this.RaisePropertyChanged("TipoCNHMotorista");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoVeiculo {
            get {
                return this.TipoVeiculoField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoVeiculoField, value) != true)) {
                    this.TipoVeiculoField = value;
                    this.RaisePropertyChanged("TipoVeiculo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UsuarioCriacao {
            get {
                return this.UsuarioCriacaoField;
            }
            set {
                if ((object.ReferenceEquals(this.UsuarioCriacaoField, value) != true)) {
                    this.UsuarioCriacaoField = value;
                    this.RaisePropertyChanged("UsuarioCriacao");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MVMCreate2.IMVMCreate")]
    public interface IMVMCreate {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMVMCreate/EmitirMVM", ReplyAction="http://tempuri.org/IMVMCreate/EmitirMVMResponse")]
        string EmitirMVM(EmitirMVM.MVMCreate2.DadosMVM item, string[] NotasFiscais);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMVMCreateChannel : EmitirMVM.MVMCreate2.IMVMCreate, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MVMCreateClient : System.ServiceModel.ClientBase<EmitirMVM.MVMCreate2.IMVMCreate>, EmitirMVM.MVMCreate2.IMVMCreate {
        
        public MVMCreateClient() {
        }
        
        public MVMCreateClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MVMCreateClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MVMCreateClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MVMCreateClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string EmitirMVM(EmitirMVM.MVMCreate2.DadosMVM item, string[] NotasFiscais) {
            return base.Channel.EmitirMVM(item, NotasFiscais);
        }
    }
}
